### ISSUE TITLE
unable to craft basic capacitors from ender-io

### ISSUE THREAD

**Issue by DingoX3** [redxblock/LastStand#20]

**Comment by DingoX3** [comment]
![2016-06-03_13 24 32](https://cloud.githubusercontent.com/assets/16032841/15787145/9b21bfe8-298e-11e6-9839-7a391f6036fa.png)

**Comment by BlakeDarwinXE** [comment]
Checked in version: 1.6
Did you check NEI?
![screen shot 2016-06-04 at 9 42 35 am](https://cloud.githubusercontent.com/assets/5892354/15800499/c1708210-2a38-11e6-8835-ed12dba37a7b.png)

**Comment by DingoX3** [comment]
yea sorry this needed to be closed. forgot
