### ISSUE TITLE
Replace BoP with Realistic Terrain Generation (RTG)

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#24]
Realistic Terrain Generation (RTG) is a mod that adds a new world type which generates realistic terrain. It doesn't add new blocks. It doesn't add new mobs. It doesn't even add new biomes. It simply generates more realistic-looking terrain for existing Overworld biomes (including those added by other mods).

URL: http://minecraft.curseforge.com/projects/realistic-terrain-generation?gameCategorySlug=mc-mods&projectID=237989

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417263

**Comment by redxblock** [comment]
voted down
