### ISSUE TITLE
Add Mod:  Minecraft Mineralogy

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#25]
Url: http://minecraft.curseforge.com/projects/minecraft-mineralogy?gameCategorySlug=mc-mods&projectID=240974

This mod replaces the generic "stone" in Minecraft with real-world rock types. Your world looks better and works Great with TC tool leveling.

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417222

**Comment by redxblock** [comment]
no, voted down.
