### ISSUE TITLE
Add Client side Mod:  Default World Generator

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#26]
http://minecraft.curseforge.com/projects/default-world-generator?gameCategorySlug=mc-mods&projectID=226188

The Default World Generator mod is a mod designed for Minecraft ModPack makers who want to have a specific world generator selected by default.  The user is still able to change it if they desire, but it will change it from "default" to what ever you specify in the config file.

**Comment by BlakeDarwinXE** [comment]
Config:
`# Configuration file

flatworld {
    # If you set world generator to flat, specify the flat template here. (Format: Qty BlockName Meta
    S:"Flat World Config" <
        2;
        1 minecraft:bedrock
        52 minecraft:sandstone
        1 minecraft:dirt 2
        ;2;
        biome_1
        village
     >
}


general {
    # Enable this to lock world generator to one specified [default: false]
    B:"Lock World Generator"=true

    # Enabling this will display all world generators installed, useful for debug [default: false]
    B:"Show World Generators in Log"=false

    # The world generator to select by default [default: default]
    S:"World Generator"=RTG
}`

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417216

**Comment by redxblock** [comment]
no, voted down.(we aren't bound by BoP we just like it. ;D)
