### ISSUE TITLE
Add Mods: Hunger Overhaul and The Spice of Life

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#29]
What is the point of having Pam's and AgriCraft is no one is going to use them.

Hunger Overhaul URL: http://minecraft.curseforge.com/projects/hunger-overhaul?gameCategorySlug=mc-mods&projectID=224476

The Spice of Life URL: http://minecraft.curseforge.com/projects/the-spice-of-life?gameCategorySlug=mc-mods&projectID=220811

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417182

**Comment by redxblock** [comment]
ahh, heck naw.
