### ISSUE TITLE
Add Mods: FloodLights

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#32]
Because more lights.

URL: http://minecraft.curseforge.com/projects/floodlights?gameCategorySlug=mc-mods&projectID=224728

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417144

**Comment by redxblock** [comment]
no

**Comment by redxblock** [comment]
# Set this to false to disable the mob-spawn prevention of the Floodlight
    B:"Floodlight: Spawn Prevention"=true

immersive has them.
