### ISSUE TITLE
Add Mod: Ocean Floor - Clay Sand and Dirt

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#37]
Spawns patches of Clay, Sand, and Dirt, within the Deep Ocean layer of boring gravel.

URL: http://minecraft.curseforge.com/projects/ocean-floor-clay-sand-and-dirt?gameCategorySlug=mc-mods&projectID=231837

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417115

**Comment by redxblock** [comment]
voted down
