### ISSUE TITLE
Add Mod: Immersive Engineering

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#42]
Immersive Engineering is a tech mod with a certain charm, based on the ideas and concepts, and with all assets created by Damien Hazard.
http://minecraft.curseforge.com/projects/immersive-engineering?gameCategorySlug=mc-mods&projectID=231951

**Comment by BlakeDarwinXE** [comment]
http://www.strawpoll.me/10417275

**Comment by redxblock** [comment]
already in the pack v3.1
