### ISSUE TITLE
Add Mod: Immersive Integration

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#43]
This mod is an addon to Immersive Engineering. The aim is to add blocks and items that fit in with the IE style but would not make sense to be in IE itself. This will be items that integrate with other mods, as well as IE and vanilla additions.
http://minecraft.curseforge.com/projects/immersive-integration?gameCategorySlug=mc-mods&projectID=232159

**Comment by DingoX3** [comment]
This mod is already in the pack.
