### ISSUE TITLE
Add a crafting recipe for the red pill

### ISSUE THREAD

**Issue by DingoX3** [redxblock/LastStand#44]
I propose we add a recipe for the red pill since we cannot locate a mad scientist and it would reduce the amount of players running around generating chunks to find him. The recipe would be 1 Android head, 1 leg, 1 arm, and 1 torso. The same amount of items required when you speak to the mad scientist.

**Comment by BlakeDarwinXE** [comment]
If you are going to remove having to look for the Mad Scientist. The Recipe should be hard. to reward players that take the time, or get lucky and find him.

**Comment by redxblock** [comment]
I'll create this for 3.3

**Comment by redxblock** [comment]
added recipe ;D
