### ISSUE TITLE
Add Specter Pack Ore Gen

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#53]
Disable Mod default Ore Gen and replaces it COFH configs. Also Added more Dense ores and fixes easy nether ores.

**Comment by redxblock** [comment]
https://github.com/redxblock/LastStand/blob/25b911f37ef8bae6d4525036d7957ec0e1eed7dc/client/curse/LastStand/overrides/config/ImmersiveEngineering.cfg

The config you checked in turns immersiveEngineering ore generation back on. Please look at trunk to see values are set to off already. ..You will need to add bauxite as an ore in your progression and disable the generation in the immersive config, and commit the change to your Specter Pack Ore Gen #53 branch.

You will need to also look at the values for the ores and make sure  to remove mod referrences for mods not in the pack example:
metalurgy.     
S:Level8=Vulcanite
S:Level9=Atlarus
in harvestlevelname

Remove those and commit that change to your Specter Pack Ore Gen #53 branch.
