### ISSUE TITLE
Review and update Mods

### ISSUE THREAD

**Issue by BlakeDarwinXE** [redxblock/LastStand#56]
There are a few mods that have update since 3.2 was released:

- AE2 Stuff
-  Another One Bites the dust
-  Apple Core
-  Guide-API
-  LootBags
-  MineFactory Reloaded
-  Nuclear Control 2
-  NuclearCraft Mod
-  Practicalities
-  Sanguimancy
-  UniDict

**Comment by redxblock** [comment]
remove AE2 stuff from the list.. no rv3 update only base code. We can not update to non-rv3 as we are using rv3 AE2 mod.
