### ISSUE TITLE
world wipe request before we get any futher

### ISSUE THREAD

**Issue by DingoX3** [redxblock/LastStand#68]
ore gen is all screwed up, tritanium doesnt pour out of smeltery to ingots or blocks(not sure what else doesnt work), quartz blowing up in gather, no quartz in nether, people starting out in gather, ferrous and shiny everywhere.

We need to pull the previous ore gen configs, and set it back to the way it was. If it aint broke dont fix it!

**Comment by BlakeDarwinXE** [comment]
Please only one problem per issue. This Modpack is still under development and so there will be bugs.

- "World wipe request before we get any further" This in not bug, that is part of testing.
- Saying "ore gen is all screwed up" doesn't help. Please explain.
- 
- 
-

**Comment by redxblock** [comment]
1.)Uni dictionary(which we all voted on)has removed a lot of those recipes you are referring to dealing with the smeltory. Honestly, I feel like we should have left it out. It doesn't care what mod you used previously. It unifies all recipes to specific machine mod, in this case mekansim from the looks of it in NEI.

2.)Ferrous, from indications on starky's mining machines it is pretty uniform with other ores on the amounts. http://imgur.com/lCV5IZN
according to the image and what we have done(doubled the ores). Copper needs to be turned down(14k really?). Ferrous is on par with osmium/tin, iron is the best behind copper. Shinny is about on par with what I would expect from the amount of ferrous coming out. Yellorium needs a boost to at least tin/osmium levels. 

3.) Quartz is in the nether just need to get to new chunks. I didn't retrogen the nether.  I put down digital miners in creative and checked multiple spots to make sure. Does it need to be turned up a notch? (could see an issue if not enough, starky's miner pulled 20 stacks last night, so i know it spawns)

4.) Quartz in the nether should explode like all the other nether ores. Keep you on your toes... (don't really see an issue here.)
