### ISSUE TITLE
Forge Lexicon needs things black-listed. 

### ISSUE THREAD

**Issue by DingoX3** [redxblock/LastStand#71]
Your able to ore dic convert a normal unstable ingot into a mobius stable/unstable ingot without doing the ritual in the End.
![2016-06-15_16 47 06](https://cloud.githubusercontent.com/assets/16032841/16097000/88ad4744-3319-11e6-8e09-29c0723b0520.png)

![2016-06-15_16 47 12](https://cloud.githubusercontent.com/assets/16032841/16097010/8e4dac52-3319-11e6-8d0e-f8ff22d2b02a.png)

**Comment by DingoX3** [comment]
![2016-06-15_16 47 12](https://cloud.githubusercontent.com/assets/16032841/16098401/c14c28ac-3320-11e6-9bee-204736d44c50.png)

**Comment by DingoX3** [comment]
you can also dupe diamonds this way. turn 1 stack into 2.5 stacks of diamonds
![2016-06-15_17 43 35](https://cloud.githubusercontent.com/assets/16032841/16098415/cc6e9b66-3320-11e6-9759-fbc6381383c6.png)

**Comment by DingoX3** [comment]
i think we should just disable the lexicon and it will solve this issue.

**Comment by redxblock** [comment]
removed both items from the lexicon-whitelist..
