### ISSUE TITLE
Biome ID Conflicts

### ISSUE THREAD

**Issue by Reveter** [redxblock/LastStand#76]
ID | Biome | Mod | Conflicting Biome
------------ | -------------| ------------ | ------------
42 | Tardis | Tardis Mod | Bamboo Forest
50 | SwampLands | BetweenLands | Coniferous Forest
51 | Coarse Islands | BetweenLands | Snowy Coniferous Forest
52 | Deep Water | BetweenLands | Crag
53 | Patchy Islands | BetweenLands | Dead Forest
54 | Marsh 1 | BetweenLands | Dead Swamp
55 | Marsh 2 | BetweenLands | Deciduous Forest
56 | Sludge Plaints | BetweenLands | Dense Forest			
91 | Chaos Corruption | Essential Craft 3 | Temperate Rainforest
92 | Frozen Corruption | Essential Craft 3 | Thicket
93 | Shadow Corruption | Essential Craft 3 | Tropical Rainforest
94 | Magic Corruption | Essential Craft 3 | Tundra
95 | Desert | Essential Craft 3 | Wasteland
96 | Dreadlands | Essential Craft 3 | Wetland
100 | Witchwood | Ars Magica 2 | Kelp Forest

**Comment by redxblock** [comment]
fixed for 3.7
